services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=librarydb
      - POSTGRES_USER=librarydb
      - POSTGRES_PASSWORD=librarydb
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: